kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.18
  commands:
    - go test ./...

- name: build
  image: golang:1.18
  commands:
    - sh .drone.sh
  depends_on:
    - test

- name: publish_latest
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-amd64
  when:
    event: [push, tag]
  depends_on:
    - build

- name: publish_alpine
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: alpine-amd64
    dockerfile: Dockerfile.alpine
  when:
    event: [push, tag]
  depends_on:
    - build

- name: publish_linux_arm
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.linux.arm
  when:
    event: [push, tag]
  depends_on:
    - build

- name: publish_linux_arm64
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.linux.arm64
  when:
    event: [push, tag]
  depends_on:
    - build

- name: publish_linux_ppc64le
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-ppc64le
    dockerfile: Dockerfile.linux.ppc64le
  when:
    event: [push, tag]
  depends_on:
    - build

- name: release
  image: plugins/github-release
  settings:
    files:
      - release/drone_*.tar.gz
      - release/drone_checksums.txt
    api_key:
      from_secret: github_token
  when:
    event: tag
  depends_on:
    - build
    
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event: [push, tag]
  depends_on:
    - publish_latest
    - publish_alpine
    - publish_linux_arm
    - publish_linux_arm64
    - publish_linux_ppc64le

