kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - sh .drone.sh

- name: publish_latest
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
  when:
    event: [push, tag]

- name: publish_alpine
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: alpine
    dockerfile: Dockerfile.alpine
  when:
    event: [push, tag]

- name: publish_linux_arm
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.linux.arm
  when:
    event: [push, tag]

- name: publish_linux_arm64
  image: plugins/docker
  settings:
    repo: drone/cli
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.linux.arm64
  when:
    event: [push, tag]

- name: release
  image: plugins/github-release
  settings:
    files:
      - release/drone_*.tar.gz
      - release/drone_checksums.txt
    api_key:
      from_secret: github_token
  when:
    event: tag
