FROM arm32v7/alpine:3.12 as alpine
RUN apk add -U --no-cache ca-certificates


FROM arm32v7/alpine:3.12

ENV GODEBUG netdns=go
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY release/linux/arm/drone /bin/

ENTRYPOINT ["/bin/drone"]
