name: Drone CLI
summary: Command line client for the Drone.
description: Command line client for the Drone continuous integration server.
  
adopt-info: drone-cli

grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  drone-cli:
    command: bin/drone-cli
    plugs:
      - docker
      - home
      - network
      - removable-media

parts:
  drone-cli:
plugin: nil 
    source: https://github.com/drone/drone-cli.git
    source-type: git
    override-pull: |
      git clone https://github.com/drone/drone-cli.git src/github.com/drone/drone-cli
       cd src/github.com/drone/drone-cli
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/drone/drone-cli
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/drone/drone-cli/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/drone/drone-cli/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/drone-cli
    build-snaps:
      - go
    build-packages:
      - git
      - sed
